#!/bin/bash
#Basic Install Script
read -p "This will install to~/.irssi/scripts and create a simlink to autostart the script. Press enter to continue or control+c to exit." continue
mkdir -p ~/.irssi/scripts/autorun/
cp -v sound.pl ~/.irssi/scripts/
[ -L $HOME/.irssi/scripts/autorun/sound.pl ] || ln -s $HOME/.irssi/scripts/sound.pl $HOME/.irssi/scripts/autorun/sound.pl
echo "Done!"
